### ISSUE TITLE
Add a demo on how to work with the swf library

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel-demos#115]

**Comment by Tembac** [comment]
Do you need a demo of this library? https://github.com/openfl/swf

If that is true, what do you think can be necesary for the demo. I'm using that library for my games and probably I can do the demo. It is really easy to use and more if you are already familiar with Flash.

**Comment by Gama11** [comment]
You probably know better what's necessary than me? :) One thing that's probably interesting is scaling assets without loss of quality.

**Comment by Gama11** [comment]
This issue has been stale for a while. Not opposed to adding more demos, but somebody would actually have to do it.

**Comment by Tembac** [comment]
Sorry, I was going to do it but I was waiting for the compatibility with latest Openfl because several things changed. I didn't knew it was going to take so long :(

**Comment by Gama11** [comment]
No worries, sorry if this came across harsher than it was meant to. :) I simply wanted to clean up the old issues here a bit (closed several similar issues with the same message).
