### ISSUE TITLE
RPG Demo Interface Firetongue Installation Bug

### ISSUE THREAD

**Issue by kkukshtel** [HaxeFlixel/flixel-demos#138]
Getting another issue semi-related to the previously closed issue re Firetongue installations.

![screen shot 2014-07-15 at 7 43 01 pm](https://cloud.githubusercontent.com/assets/7715279/3592915/035ce29c-0c7a-11e4-87e6-90e706f6c397.png)

$ lime test neko
source/FireTongueEx.hx:23: lines 23-31 : Field get_locale needed by flixel.addons.ui.interfaces.IFireTongue is missing
source/FireTongueEx.hx:23: lines 23-31 : Field locale has different property access than in flixel.addons.ui.interfaces.IFireTongue ((default,null) should be (get,null))

Not exactly sure what this is trying to tell me? Same happens for all other build targets as well.

Current structure is
usr/lib/haxe/firetongue/git

and installed using the recommended:
haxelib git firetongue https://github.com/larsiusprime/firetongue

**Comment by Gama11** [comment]
@larsiusprime Now seems like the time to release a new Firetongue version to haxelib?

**Comment by larsiusprime** [comment]
@Gama11 Absolutely, I'll get on that today along with all my flixel-ui chores once I sort a few things out with the new baby :)
