### ISSUE TITLE
FlxTween demo two buttons clicked with one  click.

### ISSUE THREAD

**Issue by nazywam** [HaxeFlixel/flixel-demos#159]
In [this](http://haxeflixel.com/demos/FlxTween/) demo, if you to click the upper part of cube ease the trail button gets clicked too.
It's not serious or anything but can be a bit anoying.
I've tried fixing it myself but I don't really understand the source.

**Comment by Gama11** [comment]
This is a result of HaxeFlixel/flixel-ui#98.
