### ISSUE TITLE
FlxBloom: FlxG.log.error does not display after compiling with linux

### ISSUE THREAD

**Issue by ruzekle** [HaxeFlixel/flixel-demos#164]
I'm going through each demo, and the FlxBloom demo, as far as I can tell, doesn't work with Ubuntu 14.04.x. When I looked at the source, it should do this command if not compiled for Flash. This comment doesn't appear. Nothing does.

		#if !flash
		FlxG.log.error("FlxBloom is only supported on Flash target for now.");
		#else

https://github.com/HaxeFlixel/flixel-demos/tree/dev/Effects/FlxBloom

**Comment by Gama11** [comment]
You probably compiled in release mode (as opposed to debug with the flixel debugger)?

**Comment by ruzekle** [comment]
Yes, that's the case. I'll run with the "lime -debug" flag from now on. Thanks.
