### ISSUE TITLE
[FlixelDemo : TiledEditor] data is missing attribute encoding

### ISSUE THREAD

**Issue by Bouffblood** [HaxeFlixel/flixel-demos#165]
When launching the game, tiles don't appear ( black screen ) and I get this error:

>    data is missing attribute encoding
 >       at haxe.xml._Fast::AttribAccess/resolve()
>	at flixel.addons.editors.tiled::TiledLayer/getByteArrayData()
>	at flixel.addons.editors.tiled::TiledLayer/get_tileArray()
>	at TiledLevel()
>	at PlayState/create()
>	at flixel::FlxGame/switchState()
>	at flixel::FlxGame/update()
>	at flixel::FlxGame/step()
>	at flixel::FlxGame/onEnterFrame()

seems like there is a problem with the XML file loader.

**Comment by Gama11** [comment]
The `level.tmx`'s data elements clearly have an `encoding` attribute, so this seems like a strange error. I can't reproduce it either, neither on master nor dev.

Are you sure you didn't make any changes to the .tmx file?

If you're still experiencing this issue, feel free to re-open it with more details (flixel / flixel-demos version etc).

**Comment by kennethdamica** [comment]
For anyone else who comes across this, I had the same problem, and solved it by changing the tiled encoding from XML to Base64 (uncompressed)

**Comment by Gama11** [comment]
Strange, that shouldn't be necessary.
