### ISSUE TITLE
Unknown identifier in new demo

### ISSUE THREAD

**Issue by xuloo** [HaxeFlixel/flixel-demos#197]
If i try and create a new project from a demo - or to build the demo projects i get this type of thing.

export/flash/haxe/DefaultAssetLibrary.hx:49: characters 51-90 : Unknown identifier : __ASSET__assets_data_data_goes_here_txt
export/flash/haxe/DefaultAssetLibrary.hx:51: characters 53-94 : Unknown identifier : __ASSET__assets_images_images_go_here_txt
export/flash/haxe/DefaultAssetLibrary.hx:53: characters 53-94 : Unknown identifier : __ASSET__assets_music_music_goes_here_txt
export/flash/haxe/DefaultAssetLibrary.hx:55: characters 53-94 : Unknown identifier : __ASSET__assets_sounds_sounds_go_here_txt
export/flash/haxe/DefaultAssetLibrary.hx:57: characters 43-74 : Unknown identifier : __ASSET__assets_sounds_beep_mp3
export/flash/haxe/DefaultAssetLibrary.hx:59: characters 45-78 : Unknown identifier : __ASSET__assets_sounds_flixel_mp3
export/flash/haxe/DefaultAssetLibrary.hx:61: characters 47-82 : Unknown identifier : __ASSET__assets_fonts_nokiafc22_ttf
export/flash/haxe/DefaultAssetLibrary.hx:63: characters 43-74 : Unknown identifier : __ASSET__assets_fonts_arial_ttf

from the flash target and this type of thing

/usr/lib/haxe/lib/openfl/git/backends/html5/openfl/display/BitmapData.hx:582: characters 27-49 : js.html.Uint8ClampedArray should be js.html.Uint8Array
/usr/lib/haxe/lib/openfl/git/backends/html5/openfl/display/BitmapData.hx:582: characters 27-49 : For function argument 'array'
/usr/lib/haxe/lib/openfl/git/backends/html5/openfl/display/BitmapData.hx:919: characters 31-49 : js.html.Uint8Array should be js.html.Uint8ClampedArray
/usr/lib/haxe/lib/openfl/git/backends/html5/openfl/display/BitmapData.hx:919: characters 31-49 : For function argument 'array'

from the html5 target

what am i doing wrong?

Haxe version 3.2.0
OpenFl version (both 3.2.2 and the 'legacy' branch from git)
haxeflixel version 3.3.11

**Comment by Gama11** [comment]
What do you mean by OpenFL version "both"? You can only have one active at a time. What's the output of `haxelib list`?

**Comment by xuloo** [comment]
I mean whichever version i have active i get the same output
