### ISSUE TITLE
Effects/FlxTrailArea

### ISSUE THREAD

**Issue by DrDerico** [HaxeFlixel/flixel-demos#199]
Dev branch.
After pressing Reset button I got an error:
[Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.

The reason is that the destroy() function is called twice. First at line 60 in ParticleState.hx, and then at line 158 in FlxTrailArea.hx

**Comment by Gama11** [comment]
Thanks - fixed by https://github.com/HaxeFlixel/flixel/commit/24920cb03d0db96a787f25b92c3c90edb745e7fb.
