### ISSUE TITLE
Replay demo...doesn't

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel-demos#216]
On Firefox and Chrome in two different keyboard layouts, Win7/x64, I tried [the replay demo (the embedded version on the demo showcase.)](http://haxeflixel.com/demos/Replay/)  I moved the mouse, clicked, used the cursors to move the player around.  That worked fine.  But then pressing R doesn't seem to do anything.

(I could have sworn that a month or two ago I tried it and it replayed just fine.  But the last three commits to it don't seem to have anything to do with whether pressing R would work, unless the reduced Main.hx causes random problems?)

If I compile and run the same code (target flash debug) it works fine locally.

**Comment by Gama11** [comment]
Nothing really wrong with the demo itself I think.
Here's what you get with the debug flash player plugin installed:

```
Error: Error #2176: Certain actions, such as those that display a pop-up window, may only be invoked upon user interaction, for example by a mouse click or button press.
	at flash.net::FileReference/_save()
	at flash.net::FileReference/save()
	at PlayState/start_play()
	at PlayState/update()
	at flixel::FlxState/tryUpdate()
	at flixel::FlxGame/update()
	at flixel::FlxGame/step()
	at flixel::FlxGame/onEnterFrame()
```

**Comment by Gama11** [comment]
Interestingly though, the original demo on http://flixel.org/features.html doesn't have this issue, so something must be different...
