### ISSUE TITLE
RPG Interface demo not running on pepper flash under linux

### ISSUE THREAD

**Issue by Rabcor** [HaxeFlixel/flixel-demos#217]
Not sure if it works on windows or not, nor if it works on adobe flash or not, but i'm using chrome with pepper flash on fedora, and all I get on the [RPG Interface demo](http://haxeflixel.com/demos/RPGInterface/) is a white blank image saying "movie not loaded" when I right click it.

**Comment by larsiusprime** [comment]
Just reproduced this on Mac with flash player; might be because I need to update the firetongue library. I'll look into it first chance I can.

**Comment by Gama11** [comment]
Happening for me on Windows as well.

@larsiusprime I don't think that's the reason - the demos were compiled using the Git version of firetongue.

**Comment by Rabcor** [comment]
Oh it displays now, not correctly, but it displays.

**Comment by Gama11** [comment]
What do you mean by "not correctly"?

**Comment by Rabcor** [comment]
I imagined it should not look like this:

http://i.imgur.com/AqTlmI9.png

**Comment by Gama11** [comment]
I think it's supposed to look like that. Might just be some leftover debug code from @larsiusprime though...

**Comment by larsiusprime** [comment]
Yeah that was an example of a new feature I added a while back, probably should put that in a more relevant place than the title screen...

**Comment by Rabcor** [comment]
I see, well thanks!
