### ISSUE TITLE
loadObject in loop of TiledEditor demo

### ISSUE THREAD

**Issue by srel90** [HaxeFlixel/flixel-demos#220]
loadObject in loop of TiledEditor demo make a multiple sprite

**Comment by Gama11** [comment]
Not sure what you mean. Could you be a little more specific?

**Comment by srel90** [comment]
so sorry about my poor English the problem is that loadobject function in tilededitor demo it is in a loop of layers so it will called multiple time for each layer  but i have solve this problem in my code  so sorry to issue this

**Comment by Gama11** [comment]
Does the issue happen with the .tmx file of the demo as well?

What's the fix?

**Comment by srel90** [comment]
im just move the line from TiledLevel.hx in red circle out of loop and the
picture is attached.

**Comment by srel90** [comment]
https://www.dropbox.com/s/19qv0tx83c35cli/Screenshot_2016-02-28-23-12-14.jpg?dl=0

**Comment by Gama11** [comment]
Oh, yeah, that line definitely shouldn't be in the loop. Each coin is generated twice in the demo right now, which nobody noticed so far because it doesn't really look any different..

Thanks for reporting this!
