### ISSUE TITLE
FlxMouseEventManager front page code outdated/broken

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel-demos#222]
http://haxeflixel.com/demos/FlxMouseEventManager/ says:

> To activate it, simply add sprites to the manager and implement the event callbacks:
> 

> ```
> import flixel.plugin.MouseEventManager;
> 
> MouseEventManager.add(new FlxSprite(), onMouseDown, onMouseUp, onMouseOver, onMouseOut); 
> 
> function onMouseDown(sprite:FlxSprite) {}
> function onMouseUp(sprite:FlxSprite) {}
> function onMouseOver(sprite:FlxSprite) {}
> function onMouseOut(sprite:FlxSprite) {}
> ```

But newbs will find that their compilers disagree, saying:

`Type not found : flixel.plugin.MouseEventManager`

**Comment by Gama11** [comment]
Thanks for reporting. More of a haxeflixel.com than a flixel-demos issue btw.

**Comment by Gama11** [comment]
https://github.com/HaxeFlixel/haxeflixel.com/commit/a188e6a839628ca0b1910d60ef8396db3f1649c1
