### ISSUE TITLE
Another FlxNapeTilemap Demo on another repo

### ISSUE THREAD

**Issue by buckle2000** [HaxeFlixel/flixel-demos#223]
This demo is an assignment of our school's CS class.
Features:
- 2 players. Use WASD and arrow keys to control.
- Rotation.
- Triple jump.
- Is-on-gound detection, using nape callbacks. (I am not using isTouching() because it does not work in FlxNapeTilemap)

Please just use the `demo` branch, since its simpler.
https://github.com/buckle2000/PlatformerWithMoment/tree/demo

**Comment by Gama11** [comment]
Are you intending to create a pull request with your improvements?

**Comment by buckle2000** [comment]
I am suprised to see it still works.

**Comment by Gama11** [comment]
Well, we have been trying to tone down the amount of breaking changes / maintain backwards compatibility with minor releases. :)
