### ISSUE TITLE
FlxBunnyMark background missing on OpenFL Next

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel-demos#228]
With OpenFL Next:

![](http://i.imgur.com/ewtUw2x.png)

With legacy:

![](http://i.imgur.com/f6cGkGY.png)

@Beeblerox Any ideas? Does `FlxStrip` simply not work on OpenFL next?

**Comment by Beeblerox** [comment]
@Gama11 have no idea. need to look closer at it

**Comment by Beeblerox** [comment]
@Gama11 hmm, it's working for me. in clean FlxBunnyMark demo, just added these two lines:
```
<set name="next" />
<haxedef name="next" />
```
at the beginning of Project.xml

**Comment by Gama11** [comment]
That's what I did as well, strange... The `<haxedef>` shouldn't be necessary btw.

I think the background is black for @larsiusprime as well?

**Comment by larsiusprime** [comment]
Yes, same here.

**Comment by larsiusprime** [comment]
If it's using DrawTriangles, I wonder if it's a graphics card driver issue. Maybe try it with ANGLE?

**Comment by larsiusprime** [comment]
Just updating on this -- I believe my solution for this was to compile lime with -DLIME_SDL_ANGLE. It seems to happen intermittently on windows machines otherwise because of something something drivers

**Comment by starry-abyss** [comment]
Maybe related to this https://github.com/HaxeFlixel/flixel/issues/1874 ?

**Comment by Gama11** [comment]
This will work as expected with OpenFL 8 (https://github.com/HaxeFlixel/flixel/pull/2136):

![](https://i.imgur.com/dK9ZpKN.gif)
