### ISSUE TITLE
FlxSpine fails to build because of missing / nonexistent haxelib "spinehaxe"

### ISSUE THREAD

**Issue by wrldwzrd89** [HaxeFlixel/flixel-demos#230]
The haxelib in question appears to have been renamed to "spinehx". So the demo needs updating.

**Comment by alihassan0** [comment]
you should probably check [this](http://forum.haxeflixel.com/topic/97/how-to-install-spinehaxe/4)

**Comment by wrldwzrd89** [comment]
Thanks, that looks to have fixed things.
