### ISSUE TITLE
Calculator build fails: Type not found

### ISSUE THREAD

**Issue by wrldwzrd89** [HaxeFlixel/flixel-demos#231]
source/State.hx:20: characters 7-19 : Type not found : hscript.Expr
source/Main.hx:6: lines 6-13 : Defined in this class

**Comment by DleanJeans** [comment]
Did you `haxelib install hscript`?

**Comment by wrldwzrd89** [comment]
I did now. Did not realize there was a haxelib called hscript. Thanks!
