### ISSUE TITLE
Make more demos mobile-compatible

### ISSUE THREAD

**Issue by rknonchalance** [HaxeFlixel/flixel-demos#232]
Since Haxeflixel demos are clones from the original Flixel demos converted to Haxe, they'd work best in Flash. But since Haxeflixel kind of does show its capability to be cross-platform on its site, I was wondering perhaps if these demos had compiler conditionals for them to work on mobile by default (or at least, have some fixes for those that have)? For example, Flixius is the only project demo I saw (so far) among the other more basic demos that has the option to compile to Android, and the Project.xml file still has a few missing directives that allows for this, such as:
<android target-sdk-version="number" if="android" />
Which should be OK for addition since it's only accepted if the build was for Android.

In addition, the Flixius project at present fails because there is another missing directive on haxedef FLX_NO_TOUCH, where there should be a conditional 'unless="mobile"' so that once it's compiled to Android the FlxTouch and FlxTouchManager classes do not fail. I hope this can be added, because otherwise the errors relate to the touches classes of FlxTouch as missing, which could somewhat lead to confusion over the origination of the error being in the library files (as I made myself, but then realized I was wrong).

**Comment by Gama11** [comment]
Most of the demos should be mobile-compatible. Unfortunately, we can't really automate this with TravisCI very well, since Android builds take so long (even on Cpp we only build Mode I believe).

I fixed the issue with Flixius, thanks! Don't hesitate to open an issue (or even a pull request) if you notice any problems with other demos.
