### ISSUE TITLE
RPGInterface doesn't showcase resizing

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel-demos#237]
This seems to be a key feature of flixel-ui, which is already coded for in RPGInterface's "battle" screen (having the wide and tall modes) that you don't see when you run the online demo, because it has a fixed resolution.

Further, there's a "tall" button in the XML that somehow gets hidden--maybe that was intended to at least show how easy it is to switch to an alternate layout?

**Comment by Gama11** [comment]
Feel free to submit a pull request with enhancements like that! :)
