### ISSUE TITLE
MinimalTD Crashes On Enemy Hit

### ISSUE THREAD

**Issue by xhunterko** [HaxeFlixel/flixel-demos#238]
While testing out MinimalTD to use as an engine base, I let one of the enemies slip through. I expected what is usually supposed to happen. A life is lost and the enemy blows up. However, what DID happen was the game crashed. I checked the flash version to see if the same thing happened. Sure enough it did.

Curious, I checked the demo page version. And yes, it crashed, and refuses to continue playing.

I do not know if this is known or how long this has been going on. I just discovered this today. I know it's not a high priority thing but it should probably be looked at.

Method: Allow an enemy to hit the goal.
Result: Game crash.

**Comment by xhunterko** [comment]
With anyone with access to pushing up code, I do not, this is easily fixed.

For a couple functions,change the following:

In the function "hitgoal" change it from:

`private function hitGoal(enemy:Dynamic, goal:Dynamic):Void`

to

`private function hitGoal(enemy:Enemy, goal:FlxSprite):Void`

In the same function, change this:

`enemy.startAtPosition(false);`

to this:

`enemy.explode(false);`

Then in the "hitenemy" function change this:

`private function hitEnemy(bullet:Dynamic, enemy:Dynamic):Void`

to this:

`private function hitEnemy(bullet:Bullet, enemy:FlxSprite):Void`

This should fix the crash.

**Comment by MSGhero** [comment]
You can make a pull request if you already know what the changes should be. Makes the maintainer's lives a bit easier. Just remember to push to dev and not master.

**Comment by xhunterko** [comment]
Again, I don't know how I would do that. I don't have github installed on the desktop and would probably break something. Which is why I asked if someone else could do it.

I tend to break things.

**Comment by MSGhero** [comment]
![image](https://cloud.githubusercontent.com/assets/5033927/17725526/1ced52d8-641a-11e6-9519-e4899f2eabdf.png)
You can do it from the browser, and your second post made it seem like you already knew how to fix the problem.

**Comment by xhunterko** [comment]
No idea if I did that correctly or not.

**Comment by MSGhero** [comment]
Almost. This is what one of mine looks like, it's going from my branch (`fastFloor`) of my fork (`MSGhero/flixel`) and going to the `dev` branch of `HaxeFlixel/flixel`. Yours is coming from the right place, but going to `xhunterko/flixel-demos` instead of `HaxeFlixel/flixel-demos`.
![image](https://cloud.githubusercontent.com/assets/5033927/17742099/a811c45a-646c-11e6-94c9-526683c9b7d9.png)

When you click the Create Pull Request button, you have the option of selecting where you want it to go.

**Comment by Gama11** [comment]
@MSGhero is correct, I merged your change manually for now. Thanks for the contribution!

**Comment by xhunterko** [comment]
Your welcome and thank you! :)
