### ISSUE TITLE
"Most of our other demos are html5 compatible."

### ISSUE THREAD

**Issue by mverleg** [HaxeFlixel/flixel-demos#250]
I get this message

> Sorry this demo requires the Flash player.
> Most of our other demos are html5 compatible.

I don't know if my browser has some problem, but there's literally only [one](http://haxeflixel.com/demos/FlxBunnymark/) demo on the site that works without Flash for me. Is that just me or is there some problem?

**Comment by Gama11** [comment]
It's a work in progress, see: https://github.com/HaxeFlixel/haxeflixel.com/issues/100 - we have only enabled the HTML5 version for that particular demo right now.

You can see the HTML5 builds for all of them here though: http://demos.haxeflixel.com/
