### ISSUE TITLE
Crash while trying to compile NeonVector for HTML5

### ISSUE THREAD

**Issue by CorruptComputer** [HaxeFlixel/flixel-demos#254]
I get the following error when trying to compile Neon Vector:

```
/usr/share/haxe/std/neko/_std/EReg.hx:33: characters 11-61 : Unsupported escaped char 's'
<builtin>:1: character 0 : Called from
/usr/share/haxe/std/neko/_std/EReg.hx:22: lines 22-204 : Called from
/home/corruptcomputer/haxelib/openfl/3,6,1/openfl/_internal/macros/MacroShader.hx:29: characters 27-165 : Called from
Aborted
```

I am using Linux, and have no clue what I am doing wrong with this, could someone help?

**Comment by Gama11** [comment]
This sounds like an issue with your setup. There seems to be a solution to this here:

http://community.openfl.org/t/solved-linux-macroshader-error/7240/4
