### ISSUE TITLE
Provide with an updated example for loading TMX.

### ISSUE THREAD

**Issue by thronecode** [HaxeFlixel/flixel-demos#258]
Since there seems to be no `layer.tilesArray` anymore, an example featuring the newest API changes would be utterly appreciated.

Is `tilesArray` really deprecated or am I missing something?

**Comment by nospoone** [comment]
I might be wrong, but isn't it called `tileArray` (singular)? My code uses

```haxe
for (tl in tileLayers) {
  var tileLayer:TiledTileLayer = tl;
  // stuff
  tilemap.loadMapFromArray(tileLayer.tileArray, width, height, Registry.IMG_PREFIX + tilesetPath + tileSheetName, 24, 24, FlxTilemapAutoTiling.OFF, 1, 1, 1);
  // more stuff
}
```

and has been working for a while now. It also seems that [it hasn't changed in forever...](https://github.com/HaxeFlixel/flixel-addons/blame/dev/flixel/addons/editors/tiled/TiledTileLayer.hx#L18) 🤔

**Comment by thronecode** [comment]
![image](https://cloud.githubusercontent.com/assets/20133696/25712482/2f2f522c-30c8-11e7-9e5c-ccaf3e2260ed.png)
Perhaps I should downgrade flixel-addons?

**Comment by thronecode** [comment]
![image](https://cloud.githubusercontent.com/assets/20133696/25712569/64aa1540-30c8-11e7-9339-8d27abb05a92.png)
Perhaps I should downgrade `flixel-addons`?

**Comment by nospoone** [comment]
Try casting the layer to `TiledTileLayer`, `TiledLayer` is the generic (not sure if that's the right term) class for `TiledTileLayer` and `TiledObjectLayer`.

I detect mine (since I use both) like this:
```haxe
for (tl in layers) {
	if (tl.type == TiledLayerType.TILE) {
		tileLayers.push(cast(tl, TiledTileLayer));
	} else { 
		objectLayers.push(cast(tl, TiledObjectLayer));
	}
}
```

But it shouldn't be an issue if you only use tile layers in your maps.

Downgrading `flixel-addons` wouldn't help as that API hasn't been touched in two years.

**Comment by Gama11** [comment]
What versions of flixel-demos and flixel-addons are you using?

**Comment by thronecode** [comment]
Thank you @nospoone (and @Gama11 as well).
Not checking for the layer type when using `loadMapFromArray` caused issues. I apologize for my leak of attention.

**Comment by nospoone** [comment]
Glad to be of service 👍
