### ISSUE TITLE
MinimalistTD demo crashes on windows

### ISSUE THREAD

**Issue by bluroman** [HaxeFlixel/flixel-demos#261]
OS: Windows 7
Tools: Flash Develop
Process:
1. Entering the "P" on first screen 
2. On the Game Screen , Push "N" to Waves. 
3. Then Below Log appeared and crashed.

Build succeeded
Done(0)
haxelib run lime run "Project.xml" neko -debug
Running process: C:\HaxeToolkit\haxe\haxelib.exe run lime run "Project.xml" neko -debug
AL lib: (EE) alc_cleanup: 1 device not closed
No valid path was passed to the enemy! Does the tilemap provide a valid path from start to finish?
Called from Enemy::followPath line 94
Called from PlayState::spawnEnemy line 808
Called from PlayState::update line 432
Called from flixel.FlxState::tryUpdate line 172
Called from flixel.FlxGame::update line 735
Called from flixel.FlxGame::step line 665
Called from flixel.FlxGame::onEnterFrame line 538
Called from openfl._legacy.events.EventDispatcher::dispatchEvent line 98
Called from openfl._legacy.display.DisplayObject::__dispatchEvent line 182
Called from openfl._legacy.display.DisplayObject::__broadcast line 161
Called from openfl._legacy.display.DisplayObjectContainer::__broadcast line 286
Called from openfl._legacy.display.Stage::__render line 1103
Called from openfl._legacy.display.Stage::__checkRender line 351
Called from openfl._legacy.display.Stage::__pollTimers line 1084
Called from openfl._legacy.display.Stage::__doProcessStageEvent line 430
Done(1)

**Comment by Gama11** [comment]
Thanks for reporting! It looks like this was caused by a bugfix in Flixel 4.3.0: https://github.com/HaxeFlixel/flixel/pull/2024
