### ISSUE TITLE
Dynamic Shadows Using Old Flixel Build?

### ISSUE THREAD

**Issue by xhunterko** [HaxeFlixel/flixel-demos#262]
So I'm trying to implement the Dynamic Shadows in my game and I've come across this error:

FlxSprite has no field fill, drawCircle, OR drawPolygon.

This may need to be updated to the latest flixel version.

I am using Flixel 4.3.0.

**Comment by JoeCreates** [comment]
These were moved into FlxSpriteUtil. You can use `using FlxSpriteUtil;`
with your imports to use them in the same way as before.
