### ISSUE TITLE
Low FPS in some demos

### ISSUE THREAD

**Issue by rositarodr** [HaxeFlixel/flixel-demos#272]
I'm having low performance in my game after upgrading to the latest versions and I have compared with some demos. With: _haxelib list_
firetongue: [git]
flixel-addons: [2.7.1]
flixel-tools: [1.4.2]
flixel-ui: [2.3.1]
flixel: [4.5.1]
hscript:  [2.3.0]
hxcpp:  [4.0.4]
lime: [7.1.1]
openfl: [8.6.4]
systools: [1.1.0]

These demos have low performance.
ProjectJumper:
![jumper](https://user-images.githubusercontent.com/44991425/48390437-5235ab80-e702-11e8-86a3-4fbc390c17f3.png)

FlxCaveGenerator:
![cave](https://user-images.githubusercontent.com/44991425/48391088-50b9b280-e705-11e8-9c0f-c9e608b722da.png)

FlxCollisions:
![collisions](https://user-images.githubusercontent.com/44991425/48391327-64194d80-e706-11e8-8481-b98d45b43224.png)

**Comment by Gama11** [comment]
Is that Neko or C++? Neko is expected to not perform as well anymore with current OpenFL versions.

If it's C++, try compiling in release instead of debug mode, that usually makes a big difference.

**Comment by rositarodr** [comment]
The screenshots are from Neko. It also happens in Android/Debug. 

If I use Android/Release the game runs smoothly, is it ok such difference between Debug/Release?

**Comment by Gama11** [comment]
It's definitely expected that there's a big performance difference between debug and release mode on targets using hxcpp.

**Comment by rositarodr** [comment]
Thanks for the info.
