### ISSUE TITLE
haxe dev version render error 

### ISSUE THREAD

**Issue by sonygod** [HaxeFlixel/flixel-demos#275]
demo :Flappybalt

haxe :haxe dev version 

flixel:git version.

![image](https://user-images.githubusercontent.com/748320/79530002-af285480-80a0-11ea-944c-056ab0bcd921.png)

![image](https://user-images.githubusercontent.com/748320/79530222-53aa9680-80a1-11ea-9426-2a22760d08bb.png)

**Comment by sonygod** [comment]
after rebuild in linux. it's work!..why ?

**Comment by Gama11** [comment]
Have you checked the browser's dev console? If you get a black screen, there's usually an error there.

**Comment by sonygod** [comment]
maybe windows or IDE issue,instead of flixel .
