### ISSUE TITLE
broken link in `about`:  www.haxeflixel.com ->  haxeflixel.com

### ISSUE THREAD

**Issue by 532910** [HaxeFlixel/flixel-demos#289]
update it please

**Comment by Geokureli** [comment]
can you be more specific?

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/150553410-d955a33f-caa4-4d69-b0f6-9b95b65358c2.png)

**Comment by Geokureli** [comment]
thanks
