### ISSUE TITLE
FlxMouseEventManager HTML5 target visual error

### ISSUE THREAD

**Issue by svandragt** [HaxeFlixel/flixel-demos#296]
Tested both macos and HTML5 as a build target.
When using html5 (reproduced by the online demo at https://haxeflixel.com/demos/FlxMouseEventManager/), when hovering over a card, the other cards temporarily disappear.

Expected result: on the macos build, the cards do not disappear.

(sound is also missing btw)

Tested in both Chrome, Safari and Firefox

**Comment by Geokureli** [comment]
I believe this is an issue with using colors on FlxSprites. I had to change the pixel perfect collision demo to use baked color animations to avoid this. Ill add this to [the list](https://github.com/HaxeFlixel/flixel-demos/issues/287)

**Comment by Geokureli** [comment]
this is fixed
