### ISSUE TITLE
Move CI that builds the demos for `demos.haxeflixel.com` to this repo

### ISSUE THREAD

**Issue by ninjamuffin99** [HaxeFlixel/flixel-demos#343]
Currently the CI that actually builds the demos for the site is at https://github.com/HaxeFlixel/demos.haxeflixel.com

which is a repo dedicated to just posting the demos for use with the haxeflixel site. I think we can instead move that stuff to this repo, and get the `demos.haxeflixel.com` github pages setup on this repo.

**Comment by Geokureli** [comment]
I think i keep forgetting to build demos because it's a separate repo, so yeah this would be simpler
