### ISSUE TITLE
rename the FlxAsepriteUtils demo to FlxAsepriteUtil?

### ISSUE THREAD

**Issue by ninjamuffin99** [HaxeFlixel/flixel-demos#346]
the flixel class is called `FlxAsepriteUtil` (no s at the end), and the demo markdown page is actually called `FlxAsepriteUtil` as well. Would there be any votes no against renaming the demo to `FlxAsepriteUtil` to match what the class is called?

**Comment by Geokureli** [comment]
![image](https://github.com/HaxeFlixel/flixel-demos/assets/2609513/8218ee85-c547-4348-9e56-3db163f37381)

**Comment by Geokureli** [comment]
![tenor](https://github.com/HaxeFlixel/flixel-demos/assets/2609513/9e1eae67-4969-4dfd-8abf-8f00ea777849)
