### ISSUE TITLE
How To Compile Source Code of HaxeFlixel Demo?

### ISSUE THREAD

**Issue by ghost** [HaxeFlixel/flixel-demos#364]

**Comment by moxie-coder** [comment]
you already opened an issue #363
don’t make duplicates

**Comment by Geokureli** [comment]
have git installled on your machine , then in your terminal run
> cd C:\<The path where you want to install the demos>

then

> git clone https://github.com/HaxeFlixel/flixel-demos.git

Then, open the demo you would like in vscode and follow this guide for running and debugging: https://haxeflixel.com/documentation/visual-studio-code/

**Comment by ghost** [comment]
oops I close

**Comment by ghost** [comment]
Run ```lime build windows``` for compile successful
