### ISSUE TITLE
DynamicShadows APK

### ISSUE THREAD

**Issue by ghost** [HaxeFlixel/flixel-demos#368]
Please Link

**Comment by Geokureli** [comment]
Bro, stop making issues like this. These aren't issues you're just asking random vague questions

**Comment by moxie-coder** [comment]
literally, like join the discord server for crying out loud if you wanna
keep asking questions like this, you’ll get better responses there

**Comment by Geokureli** [comment]
https://discord.com/invite/rqEBAgF
