### ISSUE TITLE
RPG interface issues 

### ISSUE THREAD

**Issue by mrcdk** [HaxeFlixel/flixel-demos#81]
Flash, Windows, Neko and Linux so far:
- The text "close" in the popup demo isn't centered: http://imgur.com/FCuNMxb

Neko only:
- Weird text encoding in the language radiobutton: http://imgur.com/2hyw5N0
- Throws this error when choosing Norwegian: http://pastebin.com/sBQK17an (maybe a firetongue issue)

**Comment by Gama11** [comment]
Can't reproduce any of these anymore.
